# Generated by Django 4.1.3 on 2022-12-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_pedido_first_name_pedido_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100),
        ),
    ]
