# Generated by Django 4.1.3 on 2022-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_alter_pedido_estado_alter_pedido_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=100),
        ),
    ]
