# Generated by Django 4.1.3 on 2022-12-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0002_valoracionproducto_resenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionproducto',
            name='resenia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
