# Generated by Django 4.1.3 on 2023-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0005_alter_valoracionproducto_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionproducto',
            name='valoracion',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', max_length=20),
        ),
    ]
