# Generated by Django 4.1.3 on 2023-01-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0007_alter_valoracionproducto_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='valoracionproducto',
            name='valoracion',
            field=models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], default='5', max_length=20),
        ),
    ]
