# Generated by Django 4.1.3 on 2022-12-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carritoitem_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
