# Generated by Django 4.1.3 on 2022-12-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_categoria_slug_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='slug',
            new_name='categoria_slug',
        ),
    ]
