# Generated by Django 4.1.3 on 2022-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_slug_categoria_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_popular',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
