# Generated by Django 4.1.3 on 2023-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
