# Generated by Django 4.1.3 on 2023-01-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=2, upload_to='productos'),
            preserve_default=False,
        ),
    ]
